import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import {
  OHLCVBar,
  adx,
  atr,
  bollingerBands,
  cci,
  donchianChannels,
  ema,
  ichimoku,
  keltnerChannels,
  macd,
  parabolicSar,
  roc,
  rollingPivots,
  rsi,
  sma,
  stochastic,
  supertrend,
  toColumns,
  trueRange,
  williamsR,
  zscore,
} from "./indicators";
import {
  cupAndHandle,
  doji,
  doubleTopBottom,
  engulfing,
  hammerShootingStar,
  headAndShoulders,
  insideBar,
  insideBarBreakout,
  morningEveningStar,
  threeSoldiersCrows,
  triangleWedgeBreakout,
} from "./patterns";

/**
 * Parity tests against the original Python implementation.
 *
 * `python-reference.json` is generated by running the UNMODIFIED
 * `trading_app/indicators.py` + `patterns.py` over real SPY daily bars
 * (see `tools/gen_reference_fixture.py`). If this port ever drifts - a changed
 * warm-up, a population-vs-sample std, a flipped mask - the comparison below
 * fails instead of the app quietly emitting different signals than the
 * strategies were calibrated against.
 */

interface Fixture {
  bars: number;
  columns: Record<string, Array<number | boolean | null>>;
}

const fixture = JSON.parse(
  readFileSync(join(__dirname, "python-reference.json"), "utf-8")
) as Fixture;

const col = (name: string) => fixture.columns[name];

function buildBars(): OHLCVBar[] {
  const o = col("_open") as number[];
  const h = col("_high") as number[];
  const l = col("_low") as number[];
  const c = col("_close") as number[];
  const v = col("_volume") as number[];
  return o.map((open, i) => ({ open, high: h[i], low: l[i], close: c[i], volume: v[i] }));
}

const bars = buildBars();
const df = toColumns(bars);

expect(bars.length).toBe(fixture.bars);

/** Absolute tolerance. Prices sit near 1e2-1e3, so 1e-6 is ~1e-9 relative. */
const TOL = 1e-6;

function asNumbers(values: Array<number | boolean | null>): Array<number | null> {
  return values.map((v) => (typeof v === "boolean" ? (v ? 1 : 0) : v));
}

/**
 * Compare a TS series against the Python fixture.
 *
 * NaN handling is asserted strictly (the warm-up boundary is exactly where
 * off-by-one bugs show up), and finite values within {@link TOL}.
 */
function expectMatches(name: string, actual: number[], opts: { exact?: boolean } = {}): void {
  const expected = asNumbers(col(name));
  expect(actual.length, `${name}: length`).toBe(expected.length);

  let worst = 0;
  let worstAt = -1;
  for (let i = 0; i < expected.length; i++) {
    const e = expected[i];
    const a = actual[i];
    const eNA = e === null;
    const aNA = Number.isNaN(a);

    if (eNA || aNA) {
      expect(aNA, `${name}[${i}]: expected ${eNA ? "NaN" : e} but got ${aNA ? "NaN" : a}`).toBe(
        eNA
      );
      continue;
    }
    if (opts.exact) {
      expect(a, `${name}[${i}]`).toBe(e);
      continue;
    }
    const diff = Math.abs(a - (e as number));
    if (diff > worst) {
      worst = diff;
      worstAt = i;
    }
  }
  expect(worst, `${name}: max abs error (at index ${worstAt})`).toBeLessThanOrEqual(TOL);
}

/** Compare a boolean mask, expanding the Python True/False encoding. */
function expectMaskMatches(name: string, actual: boolean[]): void {
  const expected = col(name) as Array<boolean | null>;
  expect(actual.length, `${name}: length`).toBe(expected.length);
  for (let i = 0; i < expected.length; i++) {
    expect(actual[i], `${name}[${i}]`).toBe(expected[i] === true);
  }
}

describe("parity with the Python reference (real SPY daily bars)", () => {
  it("moving averages", () => {
    expectMatches("sma20", sma(df.close, 20));
    expectMatches("ema20", ema(df.close, 20));
    expectMatches("roc10", roc(df.close, 10));
    expectMatches("zscore20", zscore(df.close, 20));
    expectMatches("rsi14", rsi(df.close, 14));
  });

  it("volatility", () => {
    expectMatches("true_range", trueRange(df));
    expectMatches("atr14", atr(df, 14));
  });

  it("MACD", () => {
    const m = macd(df.close);
    expectMatches("macd", m.macd);
    expectMatches("macd_signal", m.signal);
    expectMatches("macd_hist", m.hist);
  });

  it("Bollinger bands", () => {
    const b = bollingerBands(df.close);
    expectMatches("bb_mid", b.mid);
    expectMatches("bb_upper", b.upper);
    expectMatches("bb_lower", b.lower);
    expectMatches("bb_pct_b", b.pctB);
  });

  it("Keltner channels", () => {
    const k = keltnerChannels(df);
    expectMatches("keltner_mid", k.mid);
    expectMatches("keltner_upper", k.upper);
    expectMatches("keltner_lower", k.lower);
  });

  it("oscillators", () => {
    expectMatches("williams_r14", williamsR(df, 14));
    expectMatches("cci20", cci(df, 20));
    const s = stochastic(df);
    expectMatches("stoch_k", s.k);
    expectMatches("stoch_d", s.d);
  });

  it("ADX and directional movement", () => {
    const a = adx(df);
    expectMatches("adx", a.adx);
    expectMatches("plus_di", a.plusDI);
    expectMatches("minus_di", a.minusDI);
  });

  it("Donchian channels", () => {
    const d = donchianChannels(df);
    expectMatches("donchian_upper", d.upper);
    expectMatches("donchian_lower", d.lower);
    expectMatches("donchian_mid", d.mid);
  });

  it("Parabolic SAR", () => {
    expectMatches("psar", parabolicSar(df), { exact: false });
  });

  it("Supertrend", () => {
    const s = supertrend(df);
    expectMatches("supertrend", s.supertrend);
    expectMatches("supertrend_dir", s.direction, { exact: true });
  });

  it("Ichimoku", () => {
    const i = ichimoku(df);
    expectMatches("ichimoku_tenkan", i.tenkan);
    expectMatches("ichimoku_kijun", i.kijun);
    expectMatches("ichimoku_senkou_a", i.senkouA);
    expectMatches("ichimoku_senkou_b", i.senkouB);
    expectMatches("ichimoku_chikou", i.chikou);
  });

  it("rolling pivots", () => {
    const p = rollingPivots(df.close, 5);
    expectMaskMatches("pivot_high", p.pivotHigh);
    expectMaskMatches("pivot_low", p.pivotLow);
  });
});

describe("parity: candlestick patterns", () => {
  it("engulfing", () => expectMatches("engulfing", engulfing(df), { exact: true }));
  it("hammer / shooting star", () =>
    expectMatches("hammer_star", hammerShootingStar(df), { exact: true })
  );
  it("doji", () => expectMaskMatches("doji", doji(df)));
  it("morning / evening star", () =>
    expectMatches("morning_evening_star", morningEveningStar(df), { exact: true })
  );
  it("inside bar", () => expectMaskMatches("inside_bar", insideBar(df)));
  it("inside bar breakout", () =>
    expectMatches("inside_bar_breakout", insideBarBreakout(df), { exact: true })
  );
  it("three soldiers / crows", () =>
    expectMatches("three_soldiers_crows", threeSoldiersCrows(df), { exact: true })
  );
});

describe("parity: pivot-based chart patterns", () => {
  it("double top / bottom", () => expectMatches("double_top_bottom", doubleTopBottom(df), { exact: true }));
  it("head and shoulders", () => expectMatches("head_and_shoulders", headAndShoulders(df), { exact: true }));
  it("triangle / wedge breakout", () =>
    expectMatches("triangle_wedge", triangleWedgeBreakout(df), { exact: true })
  );
  it("cup and handle", () => expectMatches("cup_and_handle", cupAndHandle(df), { exact: true }));
});
